Repository RedHatQE/openshift-python-wrapper-data-collector, pull requests merged in 2024-10, with the labels that each got.

#197 Update import for deprecated module
  ocp_wrapper_data_collector/data_collector.py
Labels: size/XS, branch-main, verified, can-be-merged, approved-myakove

#200 Import ProjectRequest from ocp_resources.project_request
  ocp_wrapper_data_collector/data_collector.py
Labels: size/XS, branch-main, verified, can-be-merged, approved-rnetser, approved-myakove

#203 Try to import `ProjectRequest` from old modules for backward compatibility
  ocp_wrapper_data_collector/data_collector.py
Labels: size/XS, branch-main
